# Build changes before merging the PR
name: PR-CI

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Build project 🔧
        run: | 
          npm install
          npm run build
      
      - name: Run tests
        run: | 
          npm t
